"""fk+ondelete__rel+cascade

Revision ID: 214967dd7499
Revises: 95e2e40f7ef6
Create Date: 2025-11-12 18:05:02.177839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214967dd7499'
down_revision: Union[str, Sequence[str], None] = '95e2e40f7ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('options_quiz_id_fkey'), 'options', type_='foreignkey')
    op.create_foreign_key(None, 'options', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quizzes_subcategory_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'subcategories', ['subcategory_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subcategories_category_id_fkey'), 'subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'subcategories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_answers_user_id_fkey'), 'user_answers', type_='foreignkey')
    op.drop_constraint(op.f('user_answers_quiz_id_fkey'), 'user_answers', type_='foreignkey')
    op.drop_constraint(op.f('user_answers_option_id_fkey'), 'user_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_answers', 'options', ['option_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_answers', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.create_foreign_key(op.f('user_answers_option_id_fkey'), 'user_answers', 'options', ['option_id'], ['id'])
    op.create_foreign_key(op.f('user_answers_quiz_id_fkey'), 'user_answers', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(op.f('user_answers_user_id_fkey'), 'user_answers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.create_foreign_key(op.f('subcategories_category_id_fkey'), 'subcategories', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_subcategory_id_fkey'), 'quizzes', 'subcategories', ['subcategory_id'], ['id'])
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.create_foreign_key(op.f('options_quiz_id_fkey'), 'options', 'quizzes', ['quiz_id'], ['id'])
    # ### end Alembic commands ###
