"""fixed_some_fields

Revision ID: 327a715ee921
Revises: 214967dd7499
Create Date: 2025-11-13 13:04:17.258882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327a715ee921'
down_revision: Union[str, Sequence[str], None] = '214967dd7499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('options_text_key'), 'options', type_='unique')
    op.create_index('ix_quiz_single_correct', 'options', ['quiz_id'], unique=True, postgresql_where=sa.text('is_correct = TRUE'))
    op.create_unique_constraint('uq_option_quiz_text', 'options', ['quiz_id', 'text'])
    op.drop_constraint(op.f('subcategories_name_key'), 'subcategories', type_='unique')
    op.create_unique_constraint('uq_subcategory_cat_name', 'subcategories', ['category_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subcategory_cat_name', 'subcategories', type_='unique')
    op.create_unique_constraint(op.f('subcategories_name_key'), 'subcategories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_option_quiz_text', 'options', type_='unique')
    op.drop_index('ix_quiz_single_correct', table_name='options', postgresql_where=sa.text('is_correct = TRUE'))
    op.create_unique_constraint(op.f('options_text_key'), 'options', ['text'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
