"""tables: ct_sb_qz_op_ua created

Revision ID: 95e2e40f7ef6
Revises: bee62f755af3
Create Date: 2025-11-10 17:48:20.404798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '95e2e40f7ef6'
down_revision: Union[str, Sequence[str], None] = 'bee62f755af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.CheckConstraint('length(name) > 2', name='check_cat_name_gt_two'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('subcategories',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.CheckConstraint('length(name) > 2', name='check_subcat_name_gt_two'),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('quizzes',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('text', sa.String(length=500), nullable=False),
                    sa.Column('description', sa.String(length=100), nullable=True),
                    sa.Column('subcategory_id', sa.Integer(), nullable=False),
                    sa.CheckConstraint('length(text) > 2', name='check_quiz_text_gt_two'),
                    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('subcategory_id', 'text', name='uq_sub_id__sub_text')
                    )
    op.create_table('options',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('text', sa.String(length=256), nullable=False),
                    sa.Column('is_correct', sa.Boolean(), nullable=False),
                    sa.Column('quiz_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('text')
                    )
    op.create_table('user_answers',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('quiz_id', sa.Integer(), nullable=False),
                    sa.Column('option_id', sa.Integer(), nullable=False),
                    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
                    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'quiz_id', name='uq_user_quiz')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    op.drop_table('options')
    op.drop_table('quizzes')
    op.drop_table('subcategories')
    op.drop_table('categories')
    # ### end Alembic commands ###
